# Generated by Django 2.0.1 on 2018-01-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('complete_date', models.DateTimeField()),
                ('hide_from_website', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=100)),
                ('mls_url', models.CharField(max_length=250)),
                ('total_sqr_feet', models.IntegerField()),
                ('bedroom_count', models.IntegerField()),
                ('bathroom_count', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hide_from_website', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField()),
                ('sale_status', models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold'), ('P', 'Sale Pending')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('total_acres', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sale_status', models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold'), ('P', 'Sale Pending')], default='F', max_length=1)),
                ('development_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.DevelopmentPhase')),
            ],
        ),
        migrations.AddField(
            model_name='homeforsale',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Lot'),
        ),
    ]
