# Generated by Django 2.0.1 on 2018-01-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentphase',
            name='complete_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='developmentphase',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homeforsale',
            name='completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homeforsale',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homeforsale',
            name='mls_url',
            field=models.URLField(),
        ),
    ]
