# Generated by Django 2.0.1 on 2018-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20180126_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeforsale',
            options={'verbose_name_plural': 'Homes For Sale'},
        ),
        migrations.AlterField(
            model_name='homeforsale',
            name='sale_status',
            field=models.IntegerField(choices=[('FOR_SALE', 'For Sale'), ('SOLD', 'Sold'), ('SALE_PENDING', 'Sale Pending')], default=1),
        ),
        migrations.AlterField(
            model_name='lot',
            name='sale_status',
            field=models.IntegerField(choices=[('FOR_SALE', 'For Sale'), ('SOLD', 'Sold'), ('SALE_PENDING', 'Sale Pending')], default=1),
        ),
    ]
